<a href="https://colab.research.google.com/github/AdakMahato/ML/blob/Numpy/ML_ASSG1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Q1: Questions on Basic NumPy ***

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
#arr[::-1]
print(np.flip(arr))

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten())
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 1]])
print(np.array_equal(arr1,arr2))

False


(d) Find the most frequent value and their indice(s) in the following arrays:

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
val1=np.bincount(x).argmax()
print(val1)
indices=np.where(x==val1)
print(indices)

val2=np.bincount(y).argmax()
print(val2)
indices1=np.where(y==val2)
print(indices1)

1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find Sum of all elements

i)Sum of all elements

ii)Sum of all elements row-wise


iii)Sum of all elements column-wise

In [ ]:
get_config=np.get_printoptions()
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

#i
print(np.sum(gfg))
print("\n")
#ii
print(np.sum(gfg,axis=1))
print("\n")
#iii
print(np.sum(gfg,axis=0))


45


[[14]
 [16]
 [15]]


[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i) Sum of diagonal elements

ii) Eigen values of matrix

iii)Eigen vectors of matrix

iv) Inverse of matrix

v) Determinant of matrix

In [ ]:
n_array=np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
#i
print(n_array.diagonal().sum())
print('\n')

#ii
print(np.linalg.eigvals(n_array))
print('\n')

#iii
print(np.linalg.eig(n_array))
print('\n')

#iv
print(np.linalg.inv(n_array))
print('\n')

#v
print(np.linalg.det(n_array))

176


[98.16835147 28.097044   49.73460452]


EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))


[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


137180.0000000001



(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i)

p = [[1, 2], [2, 3]]   

q = [[4, 5], [6, 7]]

ii)

p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
#i
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.dot(p,q))
print('\n')
print(np.cov(p.flatten(),q.flatten()))

[[16 19]
 [26 31]]


[[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
#ii
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p,q))
print('\n')
print(np.cov(p.flatten(),q.flatten()))


[[16 19  5]
 [26 31  8]
 [46 55 14]]


[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product

In [ ]:
x=np.array([[2, 3, 4], [3, 2, 9]])
y=np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print('\n')
print(np.outer(x,y))
print('\n')
print(np.cross(x,y))

[[17 52]
 [13 62]]


[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


[[-20   4   7]
 [-84  36  20]]



# **Q2: Based on NumPy Mathematics and Statistics**




(a)
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i) Find element-wise absolute value

ii)Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.


iii)Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
#i
print(np.absolute(array))
print('\n')



[[1 2 3]
 [4 5 6]]




In [ ]:


# ii)Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
array = np.array([[1, -2, 3],[-4, 5, -6]])

flattened_array = array.flatten()

percentiles_flattened = {
    '25th': np.percentile(flattened_array, 25),
    '50th (Median)': np.percentile(flattened_array, 50),
    '75th': np.percentile(flattened_array, 75)
}
print("Percentiles of flattened array:")
print(percentiles_flattened)

percentiles_columns = {
    '25th': np.percentile(array, 25, axis=0),
    '50th (Median)': np.percentile(array, 50, axis=0),
    '75th': np.percentile(array, 75, axis=0)
}
print("Percentiles for each column:")
print(percentiles_columns)

percentiles_rows = {
    '25th': np.percentile(array, 25, axis=1),
    '50th (Median)': np.percentile(array, 50, axis=1),
    '75th': np.percentile(array, 75, axis=1)
}
print("Percentiles for each row:")
print(percentiles_rows)

Percentiles of flattened array:
{'25th': -3.5, '50th (Median)': -0.5, '75th': 2.5}
Percentiles for each column:
{'25th': array([-2.75, -0.25, -3.75]), '50th (Median)': array([-1.5,  1.5, -1.5]), '75th': array([-0.25,  3.25,  0.75])}
Percentiles for each row:
{'25th': array([-0.5, -5. ]), '50th (Median)': array([ 1., -4.]), '75th': array([2. , 0.5])}


In [ ]:
#Mean, Median and Standard Deviation of flattened array, of each column, and each row
array = np.array([[1, -2, 3],[-4, 5, -6]])

flattened_array = array.flatten()


mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_dev_flattened = np.std(flattened_array)

print("Flattened array statistics:")
print(f"Mean: {mean_flattened}")
print(f"Median: {median_flattened}")
print(f"Standard Deviation: {std_dev_flattened}")
print('\n')
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

print("Statistics for each column:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Standard Deviation: {std_dev_columns}")

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("Statistics for each row:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Standard Deviation: {std_dev_rows}")



Flattened array statistics:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224


Statistics for each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]
Statistics for each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
a=np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print('\n')
print(np.ceil(a))
print('\n')
print(np.trunc(a))
print('\n')
print(np.round(a))

[-2. -2. -1.  0.  1.  1.  3.]


[-1. -1. -0.  1.  2.  2.  3.]


[-1. -1. -0.  0.  1.  1.  3.]


[-2. -2. -0.  0.  2.  2.  3.]


# **Q3: Based on Searching and Sorting**

a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

 iii. 4 smallest elements

 iv. 5 largest elements


In [ ]:
#i
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))

[ 10  16  16  52  54  62 453]


In [ ]:
#ii
print('The indices of sorted arry with respect to its original arry is:')
print(np.argsort(array))

The indices of sorted arry with respect to its original arry is:
[0 3 4 1 5 2 6]


In [ ]:
#iii
print('Four smallest number are:')
print(np.sort(array)[:4])

Four smallest number are:
[10 16 16 52]


In [ ]:
#iv
print('Five largest number in ascending order  are:')
print(np.sort(array)[-5:])

Five largest number in ascending order  are:
[ 16  52  54  62 453]


#
Q4:

(a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)**

In [ ]:
from PIL import Image
import numpy as np


In [ ]:


def img_to_array(path):


    img = Image.open(path)


    img_array = np.array(img)

    if len(img_array.shape) == 2: # Grayscale image

        image_type = 'Grayscale'
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3: # for  RGB image

        image_type = 'RGB'
    else:
        raise ValueError("Unsupported image format")
    print(image_type)
    # Save array to a text file
    text_filename = path.rsplit('.', 1)[0] + '_array.txt'

    with open(text_filename, 'w') as f:
        if image_type == 'Gray':
            # Write grayscale array to file
            np.savetxt(f, img_array, fmt='%d')
        elif image_type == 'RGB':
            # Write RGB array to file
            # Flatten the RGB array for simplicity
            img_array_flat = img_array.reshape(-1, img_array.shape[2])
            np.savetxt(f, img_array_flat, fmt='%d', delimiter=',')

    print(f"Array saved to {text_filename}")

path = r'/content/aachen_000011_000019_leftImg8bit_foggy_beta_0.02_fake_0.png'

# Call the function
img_to_array(path)


RGB
Array saved to /content/aachen_000011_000019_leftImg8bit_foggy_beta_0.02_fake_0_array.txt
